agilgur5/react-signature-canvas

README.md
- (format): 1 sentence = 1 line for docs  …
- (fix/docs): remove `$` sign from example code block  …
- (docs): add link to `trim-canvas`  …
- (docs): add Demo section linking to new live demo  …
- (docs): modify Example section wording due to Demo
Example and Demo section are specific things to look at, the rest is just formatting. also a link was added to `getTrimmedCanvas()` description
=> various small docs improvements

package-lock.json, package.json, test-utils/configure-enzyme.js
Update `peerDependencies` range to support React 17
Fixes #58 
Closes #64 
- seems to work without any component modifications needed on React 17
- it was supposed to have "no new features" in any case
per the release blog post
- https://reactjs.org/blog/2020/10/20/react-v17.html
- ensure tests pass with React 17
- update devDeps to React 17 + react-dom 17
- update devDeps to use unofficial Enzyme Adapter for React 17
- official adapter has yet to be released, but this seems to work
for many people and the usage here is quite simple, so should be
fine for this use-case
- and tests seem to pass without issue too
- React 18 will be a separate story, but will cross that bridge
when we get there
- see more details in https://github.com/agilgur5/react-signature-canvas/pull/64#pullrequestreview- …
=> deps: update peerDeps to support React 17 without warnings

package-lock.json, package.json, webpack.config.js
- was getting a difficult-to-interpret error when running `npm start`
- https://stackoverflow.com/q/40652327/3431180
- fixed by upgrading react-hot-loader and updating the config
accordingly
This is more of a stop-gap until #42 is merged, which switches the example to use Parcel etc (and updates all devDeps)
=> fix: upgrade react-hot-loader for example to work with latest React

package-lock.json, package.json
- auto update a few hundred vulns in the devDeps
- they are just devDeps, so no impact on prod
- rest is limited by the years old build system, which will be updated
soon to something at least less old
Another small stop-gap before #42 is merged (which is also dated now)
=> env: `npm audit fix` some devDeps

babel.config.js
Optimize output by adding `assumptions` to the Babel config, which mirrors the previous build system's config that uses Babel 7.
- By previous, I mean the several year old one prior to #42 
- previously used Babel 6's preset-stage-2, which, in Babel 7, is the equivalent of turning on `loose` in `proposal-class-properties`:
https://github.com/babel/babel/tree/v7.5.5/packages/babel-preset-stage-2
- top-level `assumptions` replace the old `loose` configurations:
https://github.com/babel/rfcs/blob/main/rfcs/0003-top-level-assumptions.md#assumptions-list
- this makes the minified UMD size ~20% smaller, very close to the size it was previously w/ Babel 6
- basically the size increase was, in part, due to added spec-compliancy cases
- and we don't actually need that stricter spec-compliancy in …
=> optim: add `assumptions` to Babel config, mirroring previous config

babel.config.js
Specify a `version` in `@babel/plugin-transform-runtime`'s config to further optimize the output with newer helpers.
- the default is 7.0.0, but we are on a newer version, so we can use newer / more optimized helpers
- `createSuper` now seems to be used, which required 7.9.0:
https://github.com/babel/babel/blob/9199565fa08d840c8f1cc86c1b22be119b538f2f/packages/babel-helpers/src/helpers.ts#L624
- this seems to replace the `possibleConstructorReturn` and `getPrototypeOf` helpers
- roughly ~6% minified size decrease as a result!
- change `babel.config.js`'s caching to include `@babel/runtime`'s version since we would need to rebuild if it changes
Noticed that this was a field when stumbling upon the [`@babel/plugin-transform-runtime` options in the Babel …
=> optim: specify version in `@babel/plugin-transform-runtime`

README.md
Migrate the CI badge from Travis to GH Actions as well
- Follow-up to #84 
- use the "CI" workflow on the `main` branch only
- note that it _is_ case-sensitive, so had to put the workflow name in caps for the badge to work properly
- basically same as how the previous badge only reported on `main`
- missed this one tiny detail during the migration
- did a search this time to make sure I replaced Travis everywhere
=> docs: change CI badge to use GH Actions instead of Travis

package-lock.json, package.json, rollup.config.ts
Use [`rollup-plugin-node-externals`](https://github.com/Septh/rollup-plugin-node-externals) instead of custom `external` code
- instead of the custom JS code I wrote
- I was thinking of separating that into a plugin, but someone already did that!
- and, importantly, also covered submodules, unlike _most_ of the externals plugins (e.g. https://github.com/stevenbenisek/rollup-plugin-auto-external/issues/16)
- see regex here: https://github.com/Septh/rollup-plugin-node-externals/blob/11a7b4454f57c76436e71ecead0cc59ab0cc3b80/src/index.ts#L106
- put it _before_ `node-resolve` as the docs state
- reduces my code a bit, which is always nice, and will make it easier to split my Rollup config into its own "preset" package later on
=> deps: use `rollup-plugin-node-externals`

package-lock.json, package.json, tsconfig.json
Simplify `tsconfig.json` by using my own `tsconfig`, [`@agilgur5/tsconfig`](https://github.com/agilgur5/tsconfig).
- this is my own `tsconfig` base built on top of [`@tsconfig/strictest`](https://github.com/tsconfig/bases)
- as you can see, it just reduces all the non-type-checking related config that `@tsconfig/strictest` doesn't cover
- TS doesn't yet support package `exports` for `tsconfig`s yet (https://github.com/microsoft/TypeScript/issues/48665), hence the longer path into the package
- Relative paths in `tsconfig` bases are also relative _within_ `node_modules` (https://github.com/microsoft/TypeScript/issues/29172), so have to repeat any relative paths here
- And due to this, I think it's better right now for `build` to extend the base here instead of the `build` tsconfig in …
=> deps: use `@agilgur5/tsconfig` to simplify `tsconfig`

example/src/index.js, package-lock.json, package.json
Update `peerDependencies` range to support React 18. Update devDeps, tests, example, to support / use React 18
- Fixes #76 
- Replaces / Closes #77
- seems to work without any component modifications needed on React 18
- React 18 was mostly _deprecations_ and new features per the upgrade guide: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html
- React 18 has concurrent mode opt-in, which is technically breaking, but doesn't seem to effect this library (fortunately)
- ensure tests pass with React 18
- update devDeps to React 18, `react-dom` 18, `@types/react` 18
- update devDeps to RTL 13 which supports React 18
- see previous PR (#88) for the migration from Enzyme to RTL since Enzyme never had official support for React 17, let alone React 18
Backport this to v1.0.6, i.e. …
=> deps: update peerDeps to support React 18 without warnings

README.md
Fix badges and update a tiny bit to be more consistent with what I use today
- Similar to https://github.com/agilgur5/mst-persist/pull/35
- update/fix "build status" badge according to Shields directions: https://github.com/badges/shields/issues/8671
- remove old `nodei.co` badge
- doesn't always load and isn't very useful anymore
- removing it from all of my NPM projects
- also change Installation to a codeblock instead of just backticks
- easier to read as a block and easier to copy (full horizontal length)
- and more consistent too
=> docs: fix & update badges

.github/workflows/ci.yml
Use `node-version: [16.x]` and `os: [ubuntu-latest]` for the CI matrix to get it to pass for now
Per https://github.com/agilgur5/react-signature-canvas/pull/112#issuecomment-2566638360, Node 14 fails to "setup" and Node 16 on other OSes fails to download `node-canvas` prebuilt binaries (and then fails to build).
Node 18+ seemingly require a newer version of `node-canvas` per https://github.com/Automattic/node-canvas/issues/2025#issuecomment-1296110854, so hold off on that for a separate PR.
For now, just get CI working on a single OS and Node version.
=> fix(ci): temporarily pin matrix to Node 16 on Ubuntu

.github/workflows/ci.yml
Per https://github.com/agilgur5/react-signature-canvas/pull/112#issuecomment-2566699336 and https://docs.codecov.com/docs/codecov-tokens#uploading-without-a-token, it seems a newer version of the action is required now for tokenless uploads due to GH rate limiting etc
- `codecov-action` from `v2` to `v5`
- also had to change a setting in Codecov per [below comment](https://github.com/agilgur5/react-signature-canvas/pull/114#issuecomment-2566708449)
=> fix(ci): update `codecov-action` to v5

.github/workflows/ci.yml
Add `pull_request` to [GHA `on` config](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#using-multiple-events)
- `push` works for all PRs from my own branches, but not for PRs from forks from external contributors
- see also https://github.com/agilgur5/mst-persist/pull/33/commits/c890d142a96eb54cc768f408ad87e93d07ee8a6e
#110 and #111 are not running CI because this was missing per https://github.com/agilgur5/react-signature-canvas/issues/109#issuecomment-2561507935
=> fix(ci): run GH action on external PRs as well

.github/workflows/ci.yml, package-lock.json, package.json
Update `node-canvas` and CI matrix to use non-EoL Node
- update `node-canvas` to latest v3 to work with newer, non-EoL Node versions
- also less deps like `node-pre-gyp` etc
- update CI matrix to use LTS Node 18+
- update `actions/checkout` and `actions/setup-node` to use non-EoL Node runtimes as well
- the primary breaking change in updating [both to their](https://github.com/actions/checkout/releases/tag/v4.0.0) [respective v4 releases](https://github.com/actions/setup-node/releases/tag/v4.0.0) is the Node runtime update
- run `npm audit fix` after
- also need to update branch protection to use Node 18 as a check (instead of Node 16)
=> deps: update `node-canvas`, Node, actions, + `npm audit fix`

package-lock.json, package.json, src/index.tsx, test/index.spec.tsx
Update `peerDependencies` range to support React 19. Update devDeps, typings, tests to support / use React 19
- Fixes #109 
- Replaces / Closes #110, Closes #111
- Similar to #89
- seems to work without any source component modifications needed on React 19
- React 19 mostly removed existing deprecations and had some (nuanced) behavior changes per upgrade guide: https://react.dev/blog/2024/04/25/react-19-upgrade-guide
- [TS changes](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#typescript-changes) seem to have had some effect; minor changes to the typings were necessary
- ensure tests pass with React 19
- update devDeps to React 19, `react-dom` 19, `@types/react` 19
- update devDeps to [RTL 16.1.0](https://github.com/testing-library/react-testing-library/releases/tag/v16.1.0) …
=> deps: update peerDeps to support React 19 without warnings

package-lock.json, package.json
Update a few devdeps, mostly used in testing
- Don't want to update any build deps till after the v1.1.0 TS (#42) release so as to not alter the built output yet
- Update `jest` and related deps to latest v29.7.0 etc
- this transitively updated a bunch of Babel et al deps
- set `overrides` for the `canvas` version to ensure v3 usage
- newer `jsdom` should support this normally later: https://github.com/jsdom/jsdom/pull/3803
- Update `concurrently` to latest v9.1.2
=> deps: update `jest` et al to v29, `concurrently` to v9

README.md, example/src/index.js, example/src/styles.module.css, package.json
Update examples to latest React syntax; `createRoot` + hooks
- use `createRoot` for `react-dom` rendering
- use functional components with hooks syntax
- add link to `ref` docs
- consistently use `sigCanvas` as name
- don't switch b/t `sigPad` and `sigCanvas`
- consistently format `example/` dir with `ts-standard`
- was previously ignored for less diff, but since the example is re-written with newer syntax, good timing to reformat it too
`npm start` example runs, renders, clears, and trims
1. [ ] Update the [`gh-pages` branch](https://github.com/agilgur5/react-signature-canvas/tree/gh-pages) as well
1. [ ] Update the [`cra-example` branch](https://github.com/agilgur5/react-signature-canvas/tree/cra-example) used for the CodeSandbox as well
=> docs: update examples to use newer React syntax

README.md
Per https://github.com/agilgur5/react-signature-canvas/pull/119#issuecomment-2660163344, the CodeSandbox was migrated off of CRA as it is now deprecated (https://github.com/facebook/create-react-app/pull/17003)
- the CodeSandbox example now uses Parcel same as the `example/` dir and `gh-pages` branch
- the branch is now `codesandbox-example` as the name `cra-example` would no longer match
- left the `cra-example` branch as-is for now, so that any links to it / it's CodeSandbox continue working (still works, just uses older deps) 
- also modify some whitespace in this section for better readability of the raw markdown
=> docs: update link to new CodeSandbox example

package-lock.json, package.json
Move `@types/react` and `@types/prop-types` to `optional` `peerDependencies`
- `react` and `prop-types` are peerDeps, so their `@types/` packages should be too
- and since they're peers now, we can [mark them as optional](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#peerdependenciesmeta) as well (since they're only needed for TS usage)
- this should also allow for users to be able to install a range of `@types/react` as well, instead of just v19
- which could possibly help with the upstream DT issues I found in https://github.com/agilgur5/react-signature-canvas/issues/117#issuecomment-2646819126
This is in preparation for the v1.1.0 TS release
=> deps: move peer types to optional peerDeps

package.json
Add "100% test coverage, types, examples, & more." to the `package.json#description`
- notes all the things I've added since ~v1.0.0-ish
- this branch has been laying here for a few years now too and I think I forgot about it 😅
The NPM docs do not indicate a character limit [on `description`](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#description-1), but I was concerned about that, so also tested with `npm pack` and no errors.
I may remove the `react-signature-pad` reference eventually as this fork has now existed independently for longer than the original existed before my fork. I've been planning to "unfork" it once the TS release is finally out to simplify SEO and PRs (by default it makes my PRs go to the original repo and requires a few clicks to redirect to `main` of …
=> pkg: update description to mention current features

package-lock.json, package.json
Remove `@agilgur5/changelog-maker` from devDeps and `scripts`
- I used [my fork of `changelog-maker`](https://github.com/agilgur5/changelog-maker) for some time, but now my process is more involved
- I manually categorize, summarize, and minimize changes
- a good chunk of this could be automated by reading the semantic / conventional commit titles, but not entirely (e.g. when a change can fit multiple types or scopes)
- I use GitHub Releases' "Generate release notes" feature for the first draft / list of commits + PRs, as with [`v1.1.0-alpha.1`](https://github.com/agilgur5/react-signature-canvas/releases/tag/v1.1.0-alpha.1)
- unlike `changelog-maker`, GH's feature does not require a `PR-URL: <url>` to exist in the commits to be able to reference the PR
- I'd like to use a more …
=> deps: remove no longer used `changelog-maker` devDep

package.json
Getting an error when types aren't defined in the exports.
This is fixed after adding types to exports.
=> fix(pkg): add `types` to `package.json#exports`

package.json
Move `exports.types` to be above `exports.default` in `package.json`
Fixes https://github.com/agilgur5/react-signature-canvas/pull/126#discussion_r2017543123
- Per https://github.com/agilgur5/react-signature-canvas/pull/126#discussion_r2017543123, without this change, types are not properly detected and only happen to work [due to a TS bug](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/6ab2f0a7bf5ab4a64f57fe71df7f58506f227362/docs/problems/FallbackCondition.md) (https://github.com/microsoft/TypeScript/issues/50762. see also https://github.com/microsoft/TypeScript/issues/46334 that has this same issue)
=> fix(pkg): move `types` above `default`

package-lock.json, package.json
Update `canvas` and its deps to fix installation issues on Node 22.14+
- a `napi-build-utils` bug (https://github.com/inspiredware/napi-build-utils/issues/6) caused a bug in `prebuild-install` (https://github.com/prebuild/prebuild-install/issues/203) which causes `canvas` to fail to fetch prebuilds on Node 22.14+ per https://github.com/Automattic/node-canvas/issues/2448#issuecomment-2759866317. 
- which then causes CI to partially fail
- update the patch in the lockfile
- while at it, bump `canvas` too to a newer version with less deps
I described this in significant detail in https://github.com/Automattic/node-canvas/issues/2448#issuecomment-2759459548, linking back to the Node 22.x CI failures on #126, #130, and their merged commits (also #131 and its merged commit now)  and fortunately …
=> deps: fix install on Node 22.14+ by updating `canvas` et al
